### ISSUE TITLE
No module named behave

### ISSUE THREAD

**Issue by tomatobrown** [tokunbo/behave-parallel#8]
Any idea's on what is causing my error

I'm running:
C:\github\behave-parallel\bin\behave --processes 4 --parallel-element scenario --format plain

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named behave
Traceback (most recent call last):
  File "C:\github\behave-parallel\bin\behave", line 42, in <module>
    sys.exit(behave_main0())
  File "C:\github\behave-parallel\bin\behave", line 33, in behave_main0
    return behave_main()
  File "C:\github\behave-parallel\behave\__main__.py", line 111, in main
    failed = runner.run()
  File "C:\github\behave-parallel\behave\runner.py", line 561, in run
    return self.run_with_paths()
  File "C:\github\behave-parallel\behave\runner.py", line 583, in run_with_paths
    return self.run_multiproc()
  File "C:\github\behave-parallel\behave\runner.py", line 654, in run_multiproc
    self.joblist_index_queue = multiprocessing.Manager().JoinableQueue()
  File "C:\Python27\lib\multiprocessing\__init__.py", line 99, in Manager
    m.start()
  File "C:\Python27\lib\multiprocessing\managers.py", line 528, in start
    self._address = reader.recv()
EOFError

**Comment by tokunbo** [comment]
O_o
