### ISSUE TITLE
Pickling Error when running on Windows 7

### ISSUE THREAD

**Issue by rc65** [tokunbo/behave-parallel#9]
## Steps to Reproduce

Cloned repository to my own git repo and install it as a dependency using pip in a virtual environment.

My pip requirements file looks like this
```
enum34==1.0.4
parse==1.6.6
parse-type==0.3.4
six==1.9.0
wheel==0.24.0
git+REPO-URL@v3.0.0
```
The tag definitely exists, so it's not a problem with installing the requirement.

## What happens?

Runs fine on OS X, but on Windows the following fatal error occurs before any tests run.

```
λ behave --processes 4 --format plain --parallel-element scenario
INFO: 4 scenario(s) and 0 feature(s) queued for consideration by 4 workers. Some may be skipped if the -t option was given...
Traceback (most recent call last):
  File "c:\developer\TAS\behave-parallel-tutorial\venv\Scripts\behave-script.py", line 9, in <module>
    load_entry_point('behave==1.2.2.16', 'console_scripts', 'behave')()
  File "c:\developer\tas\behave-parallel-tutorial\venv\lib\site-packages\behave\__main__.py", line 96, in main
    failed = runner.run()
  File "c:\developer\tas\behave-parallel-tutorial\venv\lib\site-packages\behave\runner.py", line 508, in run
    return self.run_with_paths()
  File "c:\developer\tas\behave-parallel-tutorial\venv\lib\site-packages\behave\runner.py", line 513, in run_with_paths
    return self.run_multiproc()
  File "c:\developer\tas\behave-parallel-tutorial\venv\lib\site-packages\behave\runner.py", line 631, in run_multiproc
    p.start()
  File "C:\Python27\Lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\Lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\multiprocessing\forking.py", line 67, in dispatcher
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\Lib\pickle.py", line 401, in save_reduce
    save(args)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\pickle.py", line 548, in save_tuple
    save(element)
  File "C:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\Lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\Lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\Lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\Lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\Lib\pickle.py", line 748, in save_global
    (obj, module, name))
```
then
```
λ Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\Lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\Lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\Lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError
```
and finally 
`pickle.PicklingError: Can't pickle <function do_nothing at 0x00000000037BD518>: it's not found as behave.runner.do_nothing`

Any hints as to what might be causing this?

**Comment by tokunbo** [comment]
@rc65 ..4 months later... yeah, I don't know why that'd happen on Windows.

You could try removing this line: https://github.com/tokunbo/behave-parallel/blob/upstreamsync/behave/runner.py#L651

The only reason I have the do_nothing there was to keep behave silent on a bunch of warnings it'd print out.
